name: unit-tests
on: [push, pull_request]
jobs:
  unit_test:
    name: unit_test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        vim:
          - nightly
          - v9.0.0000
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.12'

      - name: Install jupyter_console
        run: |
          pip install jupyter_console

      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.vim }}

      - name: Checkout vim-replica plugin code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          uname -a
          export VIMPRG=${{ steps.vim.outputs.executable }}
          $VIMPRG --version
          cd test
          source ./run_tests.sh 1
